### ISSUE TITLE
Missing schema.sql

### ISSUE THREAD

**Issue by aepkolol** [acvigue/TranquilAPI#21]
Hey!

I deployed a cloudflare worker and made the database and buckets, however I don't have the schema for the D1 database. From reading though the code, I assumed it would be a database called "users" with 5 columns, email, password,  UUID, is_admin and is_active. However when I added myself to the database and attempted to login, I get an error I can only see in the cloudflare logs that says 

`"TypeError: Cannot read properties of undefined (reading 'replace')"`

I'm guessing it might be related to the tokens, but I'm unsure how to set that up to be honest. I see in the code 

`let token = " "`

So I guess I may need to setup a token, but honestly I'm unsure how to go about that. 

I'm way more of a robotics guy, and my code skills are mostly related to running robots, not so much backend web development. Honestly surprised I made it this far, but I built the table, setup the firmware and webpage. It's killing me that I'm hung up on server side auth code and deploying cloudflare workers. I just wanted to make pretty images in dirt. 

However, coming from a company that has a separate team to handle mechanical, electrical, frontend software and backend software, I'm pretty impressed you are solo'ing it all at once. Not all of us are a human multi-tool though ;)

**Comment by acvigue** [comment]
Ahh. I'll try to dump the database schema with workers and put it in the repo. Thanks for letting me know!

**Comment by aepkolol** [comment]
I appreciate it!

I'm unsure if that is the issue I'm facing though. If I change the tables, I get errors about it not finding the table. However with the email, password, uuid, is_admin and is_active, I just get the 

`"TypeError: Cannot read properties of undefined (reading 'replace')"`

error in the cloudflare console. I can't find any reference to "replace" in the api code, so I'm unsure what is triggering that error. 

on the tranquilVue webpage console, after I hit "Sign In" I get a different error

`TypeError: Cannot read properties of undefined (reading 'normalize')`

I hit a wall here. :(
